apiVersion: v1
baseDomain: ${baseDomain}
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform:
    aws:
      zones:
      - ${az1}
      type: ${worker-instance-type}
  replicas: ${worker-instance-count}
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform:
    aws:
      zones:
      - ${az1}
      type: ${master-instance-type}
  replicas: ${master-instance-count}
metadata:
  creationTimestamp: null
  name: ${clustername}
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: ${machine-cidr}
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  aws:
    region: ${region}
    subnets:
    - ${subnet-1}
    - ${subnet-2}
publish: External
pullSecret: '${pullSecret}'
sshKey: |
  ${sshKey}