---
kind: MachineAutoscaler
apiVersion: "autoscaling.openshift.io/v1beta1"
metadata:
  name: "CLUSTERID-worker-${az1}"
  namespace: "openshift-machine-api"
spec:
  minReplicas: 1
  maxReplicas: 12
  scaleTargetRef:
    apiVersion: machine.openshift.io/v1beta1
    kind: MachineSet
    name: "CLUSTERID-worker-${az1}"
---
kind: MachineAutoscaler
apiVersion: "autoscaling.openshift.io/v1beta1"
metadata:
  name: "CLUSTERID-workerdb2-${az1}"
  namespace: "openshift-machine-api"
spec:
  minReplicas: 1
  maxReplicas: 12
  scaleTargetRef:
    apiVersion: machine.openshift.io/v1beta1
    kind: MachineSet
    name: "CLUSTERID-workerdb2-${az1}"

